rabbit:
  image: rabbitmq:3-management
  ports:
    - "15672:15672"

celery:
  image: celery
  working_dir: /app
  command: celery worker -A tasks
  volumes:
    - .:/app
  links:
    - rabbit

db:
  image: postgres

web:
  build: .
  working_dir: /app
  command: python manage.py runserver 0.0.0.0:8000
  volumes:
    - .:/app
  ports:
    - "8000:8000"
  links:
    - rabbit
    - db